L15 active job
Lokideos/think_qna pull request #12
Opened 2019-02-06 14:22 UTC by Lokideos

В рамках данного пул реквеста был реализован следующий функционал:

* Был реализован меахнизм доставка дайджеста с новыми вопросами пользователям с помощью механизма фоновых задач;
* Пользователь может подписаться на вопрос и получать информацию о новых ответах на почту;
* Пользователь может отписаться от вопроса;
* Автор вопроса автоматически подписывается на свой вопрос.

2019-02-06 16:12 UTC, vkurennov requested changes

2019-02-06 16:12 UTC, vkurennov commented on app/models/answer.rb
> +  after_create_commit { SendNotificationJob.perform_later(question) if user.subscribed?(question) }
лучше в метод, потом с ними проще управляться

2019-02-06 16:12 UTC, vkurennov commented on app/models/question.rb
> +  scope :newly_created, -> { where('created_at > ?', 1.day.ago) }
тут не точная дата будет, могут не попасть какие-то вопросы, если, например, какое-то письмо будет сформировано в  0:05. Нужно задать четкий интервал начала и конца периода

2019-02-06 16:12 UTC, vkurennov commented on app/models/user.rb
> +    Subscription.create!(user: self, question: question) unless subscribed?(question)
используй ассоциации. раз используешь self, значит, можно все заменить через ассоциацию

2019-02-06 16:12 UTC, vkurennov commented on app/models/user.rb
> +    subscriptions.find_by(question_id: question) ? true : false
используй `exists?`

2019-02-06 16:12 UTC, vkurennov commented on app/services/notification.rb
> +  def send_notification(question)
Здесь использовать сервис - оверхэад, т.к. он не несет никакой другой логики, кроме вызова мейлера. Можно в итоге заменить вызов сервиса на вызов этой строки, так не будет лишней абстракции.

2019-02-06 16:12 UTC, vkurennov commented on spec/jobs/send_notification_job_spec.rb
> +  let(:question) { double('Question.new') }
вот это лишнее, не стоит увлекаться даблами там, где можно создать объект. даблы нужны, если мы стабим вызовы или сетап объекта сложный

2019-02-06 16:12 UTC, vkurennov commented on spec/jobs/send_notification_job_spec.rb
> +RSpec.describe SendNotificationJob, type: :job do
Сервис не верно написан. Он будет уведомлять только автора вопроса. Как уведомить остальных подписчиков - загадка.

2019-02-06 16:12 UTC, vkurennov commented on spec/models/question_spec.rb
> +    expect(question).to receive(:add_subscription)
Это ложно-положительный тест, он пройдет даже если метод будет пустым. А надо не просто вызов метода тестировать, а то, что он делает. В данном случае - проверить, что автор добавляется в подписчики

2019-02-06 16:52 UTC, Lokideos commented on app/models/user.rb
> +    subscriptions.find_by(question_id: question) ? true : false
@vkurennov тесты с ним валятся т_т В итоге пришлось использовать blank?

2019-02-07 13:45 UTC, vkurennov approved these changes

2019-02-07 23:09 UTC, merged