L16 fulltext search
Lokideos/think_qna pull request #13
Opened 2019-02-19 14:13 UTC by Lokideos

В рамках данного пул реквеста был реализован следующий функционал:
* Была произведена первичная настройка Sphinx search engine;
* Был реализован поиск по вопросам, ответам, комментариям и пользователям;
* Был реализован глобальный поиск.

2019-02-20 09:38 UTC, vkurennov requested changes

2019-02-20 09:38 UTC, vkurennov commented on app/models/search.rb
> +class Search < ApplicationRecord
Это не имеет смысла делать AR-моделью. История поиска - это не сам поиск, да и не нужна она по заданию, поэтому лучше сделать это сервисным классом, это как раз то, для чего и нужны такие классы.

2019-02-20 09:38 UTC, vkurennov commented on app/models/search.rb
> +class Search < ApplicationRecord
А если хочется чтобы класс вел себя как модель, но при этом моделью не являлся (назначение атрибутов, валидации и т.п.) , то можно в любой класс подключить [модуль ActvieModel ](https://guides.rubyonrails.org/active_model_basics.html)(или только нужные подклассы) и будет все как надо.

2019-02-20 09:38 UTC, vkurennov commented on app/models/search.rb
> +  validate :correct_search_type
это можно стандартной валидацией на inclusion сделать

2019-02-20 09:38 UTC, vkurennov commented on app/views/searches/show.html.slim
> +      - if result.is_a?(Question)
Вместо if лучше сделать для каждого типа свой паршл, чтобы имя паршла совпадало с именем типа и тогда, используя метод `underscore`, легко из имени класса получить имя паршала и отрендерить его.

2019-02-20 09:38 UTC, vkurennov commented on spec/controllers/searches_controller_spec.rb
> +        expect { post :create, params: { search: attributes_for(:search) } }.to change(Search, :count).by(1)
тут лучше проверять, что вызывается нужный класс с нужными параметрами

2019-02-20 09:38 UTC, vkurennov commented on spec/models/search_spec.rb
> +  describe '#perform_search' do
тут надо проверить, что поиска не будет, если валидация не прошла, потому что ничего сейчас не мешает вызвать этот метод даже на невалидных значениях

2019-02-20 13:42 UTC, Lokideos commented on spec/controllers/searches_controller_spec.rb
> +        expect { post :create, params: { search: attributes_for(:search) } }.to change(Search, :count).by(1)
@vkurennov не совсем понял, что имеется ввиду.

2019-02-20 14:55 UTC, vkurennov commented on spec/controllers/searches_controller_spec.rb
> +        expect { post :create, params: { search: attributes_for(:search) } }.to change(Search, :count).by(1)
mesage expectation: проверить, что у сервисного класса вызван нужный метод с нужными параметрами

2019-02-20 14:58 UTC, vkurennov requested changes

2019-02-20 14:58 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +    Services::Search.new(cookies['search.query'], cookies['search.search_type'])
а зачем это через куки делать?

2019-02-20 14:58 UTC, vkurennov commented on app/services/search.rb
> +  validates :query, :search_type, presence: true
валидации также в начале класса, до конструктора должны быть

2019-02-20 14:58 UTC, vkurennov commented on spec/controllers/searches_controller_spec.rb
> +      ThinkingSphinx::Test.run { get :search_result }
тут как раз не нужно реальный поиск запускать, а все решить через стабы и message expectations

2019-02-20 14:58 UTC, vkurennov commented on spec/controllers/searches_controller_spec.rb
> +RSpec.describe SearchesController, type: :controller do
Здесь не хватает самого главного - проверки, что поиск выполняется. И сделать это надо через message expectations

2019-02-20 18:03 UTC, Lokideos commented on app/services/search.rb
> +  validates :query, :search_type, presence: true
@vkurennov понял. Я почему-то подумал, что первым всегда конструктор должен идти.

2019-02-20 18:36 UTC, Lokideos commented on spec/controllers/searches_controller_spec.rb
> +RSpec.describe SearchesController, type: :controller do
@vkurennov кажется, сделал

2019-02-21 10:49 UTC, vkurennov requested changes

2019-02-21 10:49 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +    unauthorized! if cannot? :search, :general_search
лучше делать так:
`authorize! :search, :general_search`

2019-02-21 10:49 UTC, vkurennov commented on spec/controllers/searches_controller_spec.rb
> +  describe 'GET #search_result' do
Ты тестируешь уже детали реализации, а надо проверять вызов твоего сервисного класса. Он же отдельно протестирован. Поэтому и надо проверить вызов именно этого класса.

2019-02-22 08:53 UTC, vkurennov requested changes

2019-02-22 08:53 UTC, vkurennov commented on spec/controllers/searches_controller_spec.rb
> +    let(:service) { double('Services::Search.new(params["query"], params["search_type"])') }
смысл делать new в double нет, там же не код, а просто строка

2019-02-22 08:53 UTC, vkurennov commented on spec/controllers/searches_controller_spec.rb
> +    before { allow_any_instance_of(SearchesController).to receive(:search_service).and_return(service) }
Лучше вот так:

```
let(:service) { double('Services::Search') }
before { allow(Services::Search).to receive(:new).and_return(service) }
```
т.е. стабим интсанциирование сервиса и подставляем свой объект.

2019-02-22 08:53 UTC, vkurennov commented on spec/controllers/searches_controller_spec.rb
> +    context 'with questions' do
Здесь нам не надо проверять сам поиск и результат. Это мы делаем в тестах самого сервиса. Здесь нам надо проверить, что у сервиса вызывается нужный метод с нужными парамтерами. Т.е. не allow использовать, а expect для сервиса. И тогда тестов будет меньше, но они будут тестировать суть - то, что вызывается сервис поиска с нужными параметрами. А что он вернет, на сам контроллер не влияет.

2019-02-23 15:03 UTC, vkurennov approved these changes

2019-02-24 11:00 UTC, merged