L6 acceptance tests
Lokideos/think_qna pull request #3
Opened 2018-12-23 18:09 UTC by Lokideos

В рамках данного пул рквеста был реализован следующий функционал:
1) Был подключен travis для тестирования перед деплоим и мерджем в мастер (не уверен, что корректно его подключил, правда :( );
2) Применяя парадигму разработки BDD были реализованы следующие истории пользователей:
* Пользователь может создавать вопрос;
* Пользователь может просматривать список вопросов;
* Пользователь, находясь на странице вопроса, может написать ответ на вопрос;
* Пользователь может просматривать вопрос и ответы к нему;
* Пользователь может войти в систему;
* Пользователь может выйти из системы;
* Пользователь может зарегистрироваться в системе;
* Только аутентифицированный пользователь может создавать вопросы и ответы;
* Автор может удалить свой вопрос или ответ, но не может удалить чужой вопрос/ответ.

2018-12-24 10:40 UTC, vkurennov requested changes

2018-12-24 10:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question, notice: "Answer wasn't created; check your input."
Нельзя делать редирект при ошибках валидации, так ты потеряешь и информацию об ошибках и все, что ввел юзер и не сможешь адекватно указать на ошибки и дать юзеру возможность исправить то, что он ввел

2018-12-24 10:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question, notice: "Answer wasn't created; check your input."
Нужно делать рендер той страницы, на которой была форма

2018-12-24 10:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def index
Бессмысленно смотреть просто список всех ответов в системе, без вопросов это будет несвязанный набор. Ответы имеют смысл только в контексте вопроса, поэтому и отображаются на странице вопроса, значит общий список не нужен. Также не нужен new, т.к. форма отображается на странице вопроса

2018-12-24 10:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to root_path unless current_user.author_of?(answer)
Пожалуй, стоит вывести еще какое-то сообщение, а не просто сделать редирект

2018-12-24 10:40 UTC, vkurennov commented on app/models/user.rb
> +    resource.user == self
Лучше сравнивать по user_id, т.к. в текущем варианте ты каждый раз делаешь запрос к базе, вытягивая ассоицацию user, что приведет к проблеме n+1 запроса

2018-12-24 10:40 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    = form_with model: [question, @answer] do |f|
Здесь тоже надо выводить ошибки валидации

2018-12-24 10:40 UTC, vkurennov commented on app/views/shared/_header.html.slim
> +  - if user_signed_in?
А если не залогинен, стоит показывать ссылку на вход

2018-12-24 10:40 UTC, vkurennov commented on db/migrate/20181223171233_add_foreign_keys_to_questions_and_answers.rb
> +    add_belongs_to :questions, :user
Стоит указыавть опцию foreign_key: true, чтобы включить контроль целостности на уровне базы

2018-12-24 10:40 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
В этом контексте надо еще проверить связь созданного ответа с залогиненным юзером

2018-12-24 10:40 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'used by user, who is not author of the answer' do
Какой в этом контексте рендер/редирект?

2018-12-24 10:40 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
Тут также надо проверить связь с залогиненным юзером

2018-12-24 10:40 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'used by user, who is not author of the question' do
Какой тут рендер/редирект?

2018-12-24 10:40 UTC, vkurennov commented on spec/features/answer/create_answer_for_question_spec.rb
> +      expect(page).to have_content "Answer wasn't created; check your input."
надо проверить еще и сами ошибки валидации, а не только флеш-сообщение

2018-12-24 10:40 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    within('.answers') { expect(page).to_not have_content 'Delete answer' }
лучше have_link здесь использовать

2018-12-24 10:40 UTC, vkurennov commented on spec/models/user_spec.rb
> +        expect(author.author_of?(question)).to be_truthy
Есть более красивый синтаксис для методов-предикатов: `expect(author).to be_author_of(question)`, т.е. переносим вызов метода в правую часть, добавляем к нему be_ и убираем вопр. знак.
Только для красоты, стоит author переименовать в user

2018-12-24 12:31 UTC, Lokideos commented on db/migrate/20181223171233_add_foreign_keys_to_questions_and_answers.rb
> +    add_belongs_to :questions, :user
@vkurennov ох, точно, да

2018-12-25 07:47 UTC, vkurennov approved these changes

2018-12-25 07:47 UTC, vkurennov commented on app/models/user.rb
> +    resource.user.id == id
Так ты от проблемы не избавился, ты по-прежнему вытягиваешь ассоциацию user из базы и у нее берешь id, но ведь объект, у которого есть ассоциацию с юзером, уже содержит поле user_id, и взяв его, ты получишь сразу id без лишнего запроса к базе

2018-12-25 14:51 UTC, Lokideos commented on app/models/user.rb
> +    resource.user.id == id
@vkurennov поправил на `resource.user_id == id`

2018-12-26 14:30 UTC, merged