L7 rails ajax
Lokideos/think_qna pull request #4
Opened 2019-01-07 13:54 UTC by Lokideos

В рамках данного пул реквеста с использованием технологии AJAX был реализован следующий функционал:
* Создание ответов к вопросам;
* Только автор теперь может редактировать его вопросы и ответы;
* Удаление ответов было переделано на AJAX;
* Автор вопроса может выбрать лучший ответ на свой вопрос;
* Автор вопроса может выбрать другой лучший ответ на свой вопрос; при этом предыдущий лучший ответ вернется в общий список ответов;
* Лучший ответ отображается над общим списком ответов.

2019-01-08 09:59 UTC, vkurennov requested changes

2019-01-08 09:59 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    answer.choose_best_answer
Здесь должна быть проверка на автора **вопроса**

2019-01-08 09:59 UTC, vkurennov commented on app/models/answer.rb
> +  after_update :two_best_answers_exception
Если применить стандартную валидацию на уникальность, то не придется вручную писать проверки и выброс исключения. Старайся максимум работы перекладывать на фреймворк.

2019-01-08 09:59 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>        it 'redirects to the questions show view' do
Поправь описания тестов, чтобы они соответсвовали их содержимому.

2019-01-08 09:59 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      expect(answer.best).to be_truthy
Лучше писать так: `expect(answer).to be_best`

2019-01-08 09:59 UTC, vkurennov commented on spec/features/question/choose_best_answer_spec.rb
> +    scenario "tries to choose best answer for other user's question via PATCH request" do
Это не уровень  acceptance-тестов, это уровень тестов контроллера. Именно там мы можем тестировать прямые запросы. В acceptance-тестах можно тестировать лишь то, что пользователь может делать через интерфейс приложения

2019-01-08 09:59 UTC, vkurennov commented on spec/features/question/choose_best_answer_spec.rb
> +    scenario 'tries to choose best answer via patch request' do
Опять же, такие вещи тестируются на уровне контроллеров

2019-01-08 09:59 UTC, vkurennov commented on spec/features/question/update_spec.rb
> +      scenario "tries to update other user's question via PATCH request" do
Это выносится на уровень контроллеров (и в общем-то, оно там уже есть)

2019-01-08 09:59 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'PATCH #choose_best' do
Тут не хватает теста, когда идет запрос от не-автора вопроса

2019-01-08 09:59 UTC, vkurennov commented on spec/features/question/update_spec.rb
> +    scenario 'tries to update the question via PATCH request' do
И снова тест не того уровня

2019-01-08 09:59 UTC, vkurennov commented on spec/models/answer_spec.rb
> +        expect(answer.best).to be_truthy
И опять же лучше писать так: `expect(answer).to be_best`

2019-01-08 09:59 UTC, vkurennov commented on spec/models/answer_spec.rb
> +        expect(second_answer.best).to be_falsey
`expect(second_answer).to_not be_best`

2019-01-08 15:15 UTC, Lokideos commented on app/models/answer.rb
> +  after_update :two_best_answers_exception
@vkurennov Я в итоге упростил валидацию, но со стандартной валидацией на уникальность у меня не получилось `:(`
Я в коде закомментировал то, что я пытался сделать и ошибку, которая выпадала.

2019-01-09 08:33 UTC, vkurennov approved these changes

2019-01-09 08:33 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def filter_question_non_author_users
Тут сомнительно, нужен ли метод для этого, ведь проверка только в одном месте нужна.

2019-01-09 08:33 UTC, vkurennov commented on app/models/answer.rb
> +  default_scope { order(created_at: :asc) }
А чего у тебя дефолтный скоуп затесался между методами? Все макросы всегда записываются в начале класса, чтобы их видно было

2019-01-09 08:33 UTC, vkurennov commented on app/models/answer.rb
> +  # validates :best, uniqueness: { scope: :answers_of_related_question }
ты путаешь опцию scope у валидации на уникальность и именованые скоупы моделей. Название одно, но это разные вещи. В валидации мы указываем по каким полям мы смотрим уникальность в таблице. Например, у нас в таблице answers есть поля best и question_id, мы должны проверять уникальность только "в рамках" question_id, т.е. с данным question_id может быть только одна запись с best: true. 

Но тут действительно эту валидацию применить не получится, я ошибся. Потому что значения false будет не уникальным и оно может быть у нескольких ответов. Поэтому тут действительно решается через кастомную валидацию, как ты в итоге и сделал.

2019-01-09 08:33 UTC, vkurennov commented on app/models/answer.rb
> +    errors.add(:best, I18n.t('errors.best_answer_uniqueness')) if best == true && question.answers.find_by(best: true)
Не надо сравнивать с true/false никогда. Если ты напишешь `if best && ...` будет то же самое. А для false используется отрицание. Такие сравнения всегда выдают код новичка и выглядят непрофессионально. Ну это так, на будущее.

2019-01-09 08:33 UTC, vkurennov commented on spec/features/answer/update_spec.rb
> +      scenario "tries to update other user's answer via PATCH request" do
Опять тест не того уровня, я тебе писал об этом ранее. Не должно быть на уровне фича-тестов проверок на запросы. Это уровень тестов контроллера.

2019-01-09 08:33 UTC, vkurennov commented on spec/features/answer/update_spec.rb
> +    scenario 'tries to update answer via PATCH request' do
Снова лишний тест

2019-01-09 11:14 UTC, merged