L10 ajajson conerns
Lokideos/think_qna pull request #7
Opened 2019-01-17 17:25 UTC by Lokideos

В рамках данного пул реквеста был реализован следующий функционал:
1) Пользователь может оценивать вопросы или ответы. При этом:
* пользователь может оценитвать вопросы или ответы только один раз подряд;
* пользователь не может оценивать свои вопросы и ответы;
* пользователь может изменить результаты своей оценки вопроса или ответы.

2019-01-18 09:40 UTC, vkurennov requested changes

2019-01-18 09:40 UTC, vkurennov commented on app/assets/javascripts/answers.js
> +        $(this).closest('.answer-instance').find('.answer-rating-value').html('<p>Rating: ' + answer_rating.score + '</p>');
Все эти closest + parent + children + find во-первых, медленные, во-вторых, ненадежные. стоит чуток поменять верстку и весь код упадет. Гораздо лучше использовать css-селекторы. Если с сервера вернуть тип и id объекта, за который был голос, то легко будет составить такой селектор (при условии, что в макете в id нужного элеимента будет включен id объекта)

2019-01-18 09:40 UTC, vkurennov commented on app/assets/javascripts/questions.js
> +    $('.question-rating').on('ajax:success', '.like-link', function(e) {
Почему для вопросов и ответов обработка так сильно различается? Ведь по идее, она должна работать универсально. Попробуй сделать так, чтобы обработчики были одтинаковыми и для вопросов и для ответов. В итоге, у тебя должен получиться вообще один обработчик, а для вопросов он или для ответов, будет зависеть от типа объекта, который вернет сервер.

2019-01-18 09:40 UTC, vkurennov commented on app/models/concerns/ratable.rb
> +    # Should I test it?
Yes, of course

2019-01-18 09:40 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    Rating.create(ratable: answer) if @answer.save
Ты это делаешь в коллбеках модели

2019-01-18 09:40 UTC, vkurennov commented on app/models/concerns/ratable.rb
> +      Rating.create(ratable: self)
Работай с ассоциациями: `rating.create`

2019-01-18 09:40 UTC, vkurennov commented on app/models/rating.rb
> +    raise StandardError, "User can't rate his resources" if ratable_author == user
Используй  метод  `User#author_of?` для сравнения юзера с владельцем ресурса

2019-01-18 09:40 UTC, vkurennov commented on app/models/rating.rb
> +    Rating.transaction do
Транзакция откатывается только в случае исключения, поэтому нужно использовать bang-версии методов.

2019-01-18 09:40 UTC, vkurennov commented on app/models/rating.rb
> +    !rating_changes.where(rating_id: self, user_id: user, status: value).first
Тут кажется, отрицание меняет суть метода на противоположный. Из названия метода ожидается, что метод вернет true, если голос уже есть и false, если его нет. А у тебя наоборот.

2019-01-18 09:40 UTC, vkurennov commented on app/models/rating.rb
> +    rating_changes.where(rating_id: self, user_id: user).first
Тут нужна меомизация, у тебя этот метод внутри других по нескольку раз вызывается и на каждый его вызов заново из базы загружается объект.

2019-01-18 09:40 UTC, vkurennov commented on app/models/rating.rb
> +    ratable_type.classify.constantize.find(ratable_id).user
У тебя же полиморфная ассоциация. Она уже есть. Не надо изобретать велосипед. Просто обратись к ней как к ratable и получишь нужны объект. Рельсы все уже делают за тебя, нужно им только не мешать

2019-01-18 09:40 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +            = link_to t('.like'), like_answer_path(answer), class: 'rate-answer-link like-link hidden', method: :patch, data: { type: :json }, remote: true
Ради одного дополнительного класса дублировать всю строку - это перебор. Подумай, как можно только класс добавлять, а остальную строку оставить как есть

2019-01-18 09:40 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +            = link_to t('.like'), like_answer_path(answer), class: 'rate-answer-link like-link hidden', method: :patch, data: { type: :json }, remote: true
И далее то же самое

2019-01-18 09:40 UTC, vkurennov commented on app/views/questions/show.html.slim
> +          .rating-links
1. Посмотри замечания к аналогичному блоку для ответов
2. Попробуй сделать универсальный паршл для голсоования. Для путей есть замечательный [polymorphic_path](https://api.rubyonrails.org/classes/ActionDispatch/Routing/PolymorphicRoutes.html)

2019-01-18 09:40 UTC, vkurennov commented on spec/features/answer/rate_answer_spec.rb
> +      sleep(2)
у тебя же есть wait_for_ajax, зачем еще sleep, да еще и на 2 сек?

2019-01-18 09:40 UTC, vkurennov commented on spec/features/answer/rate_answer_spec.rb
> +    scenario 'unlikes the answer', js: true do
Тут еще бы проверить, что рейтинг вернулся обратно

2019-01-18 09:40 UTC, vkurennov commented on spec/models/rating_change_spec.rb
> +  rescue ActiveRecord::RecordInvalid => e
Очень плохой подход отлавиливать в тестах исключение и в них что-то проверять. Лучше тогда и проверять выброс исключения (`to raise_error`)

2019-01-18 09:40 UTC, vkurennov commented on spec/models/rating_spec.rb
> +      rescue StandardError => e
Проверяй сам выброс исключения

2019-01-18 09:40 UTC, vkurennov commented on spec/models/rating_spec.rb
> +      rescue StandardError => e
Проверяй сам выброс исключения

2019-01-18 09:40 UTC, vkurennov commented on spec/models/rating_spec.rb
> +        expect(rating.rated?(user)).to be_a(RatingChange)
Вот это тоже плохо, метод-предикат должен возвращать true/false,  а не объект.

2019-01-19 14:40 UTC, Lokideos commented on app/models/rating.rb
> +    rating_changes.where(rating_id: self, user_id: user).first
@vkurennov как бы мне не забывать использовать этот крутой паттерн т_т

2019-01-19 16:41 UTC, Lokideos commented on spec/features/answer/rate_answer_spec.rb
> +      sleep(2)
@vkurennov в аплоадах для загрузки файлов на Амазон, а здесь я пытался решить проблему запуска этих тестов при прогонке всех тестов, но не вышло :(

2019-01-20 10:31 UTC, vkurennov approved these changes

2019-01-20 10:31 UTC, vkurennov commented on app/models/rating.rb
> +  def do_not_allow_author_to_rate(user)
длинноватые у тебя названия методов, это не всегда хорошо. Лучше что-то вроде check_user, т.е. понятно, что делает, но без лишних подробностей. Краткость - сестра таланат, как гооврится ))

2019-01-20 14:52 UTC, merged